services:
  - type: web
    name: everest-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://everestdevelopmet:everestrestaurantcookmail@everest.ppovmhz.mongodb.net/?retryWrites=true&w=majority&appName=Everest
      - key: JWT_SECRET
        value: a_very_secret_jwt_key_that_is_long
      - key: JWT_EXPIRE
        value: 30d
      - key: CLIENT_URL
        value: https://everestrestaurantglobalcooking.vercel.app
      - key: FRONTEND_URL
        value: https://everestrestaurantglobalcooking.vercel.app
      - key: BACKEND_URL
        value: https://everestrestaurantglobalcookmail.onrender.com
      - key: ADMIN_EMAIL
        value: mustafoyevdevelopment@gmail.com
      - key: EMAIL_USER
        value: mustafoyevdevelopment@gmail.com
      - key: EMAIL_PASS
        value: lcsd wbpv ksup gdjd
      - key: PAYME_MERCHANT_ID
        value: test_merchant_id
      - key: PAYME_SECRET_KEY
        value: test_secret_key
      - key: SOCKET_CORS_ORIGIN
        value: https://everestrestaurantglobalcooking.vercel.app
      - key: SMTP_USER
        value: mustafoyevdevelopment@gmail.com
      - key: SMTP_PASS
        value: lwpz wecs fnqr pvgq 